"""initial_schema

Revision ID: 5bfa46f27d43
Revises: 
Create Date: 2026-05-16 23:14:31.447548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfa46f27d43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_service_categories_slug'), 'service_categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'WORKER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'PENDING', 'BLOCKED', 'SUSPENDED', name='accountstatus'), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_history', sa.JSON(), nullable=True),
    sa.Column('device_tokens', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('admin_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_action_type'), 'admin_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_created_at'), 'admin_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_actions_target_id'), 'admin_actions', ['target_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('service_category', sa.String(), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=False),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('service_address', sa.JSON(), nullable=False),
    sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preferred_time_slot', sa.String(), nullable=False),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=True),
    sa.Column('estimated_price', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('platform_commission', sa.Float(), nullable=True),
    sa.Column('worker_payout', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'WORKER_ENROUTE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='bookingstatus'), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'REFUNDED', 'FAILED', name='paymentstatus'), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('materials_required', sa.JSON(), nullable=True),
    sa.Column('ai_recommended_workers', sa.JSON(), nullable=True),
    sa.Column('ai_price_confidence', sa.Float(), nullable=True),
    sa.Column('fraud_detection_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('addresses', sa.JSON(), nullable=True),
    sa.Column('payment_preferences', sa.JSON(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('wallet_balance', sa.String(), nullable=True),
    sa.Column('preferred_worker_ids', sa.JSON(), nullable=True),
    sa.Column('service_history', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_category', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('government_id_type', sa.String(), nullable=True),
    sa.Column('government_id_number', sa.String(), nullable=True),
    sa.Column('government_id_document', sa.String(), nullable=True),
    sa.Column('police_verification_document', sa.String(), nullable=True),
    sa.Column('address_proof_document', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SUSPENDED', name='workerstatus'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('working_radius_km', sa.Integer(), nullable=True),
    sa.Column('available_timings', sa.JSON(), nullable=True),
    sa.Column('base_charge_per_hour', sa.Float(), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=True),
    sa.Column('emergency_charge_multiplier', sa.Float(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('ifsc_code', sa.String(), nullable=True),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('self_intro_video', sa.String(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('languages_spoken', sa.JSON(), nullable=True),
    sa.Column('total_jobs_completed', sa.Integer(), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('response_time_avg', sa.Float(), nullable=True),
    sa.Column('cancellation_rate', sa.Float(), nullable=True),
    sa.Column('ai_profile_score', sa.Float(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'BLOCKED', name='slotstatus'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slots_start_time'), 'availability_slots', ['start_time'], unique=False)
    op.create_index(op.f('ix_availability_slots_worker_id'), 'availability_slots', ['worker_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('complaint_type', sa.Enum('WORKER_BEHAVIOR', 'SERVICE_QUALITY', 'PAYMENT_ISSUE', 'OVERCHARGING', 'NO_SHOW', 'DAMAGE', 'OTHER', name='complainttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'CLOSED', name='complaintstatus'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('refund_approved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_booking_id'), 'complaints', ['booking_id'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_customer_id'), 'complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_worker_id'), 'complaints', ['worker_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'WALLET', 'CASH', 'NET_BANKING', name='paymentmethod'), nullable=False),
    sa.Column('gateway_order_id', sa.String(), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_reason', sa.String(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('gateway_order_id'),
    sa.UniqueConstraint('gateway_transaction_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('reviewed_user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('key_phrases', sa.JSON(), nullable=True),
    sa.Column('is_flagged_fake', sa.Boolean(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('reported_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_index(op.f('ix_complaints_worker_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_booking_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_availability_slots_worker_id'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_start_time'), table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_table('worker_profiles')
    op.drop_table('customer_profiles')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_admin_actions_target_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_created_at'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_action_type'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_categories_slug'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
